'use client';

import { FormEvent, useMemo, useState } from 'react';
import Link from './internal-link';
import { useSiteLocale } from './site-localization';
import { getArticleBySlug, getCategoryArticleGroups, getCategoryBySlug, getHelpCenterStats, getPublishedCategories, getPublishedArticles, searchHelpArticleResults, searchHelpArticles } from '../../lib/help-center/index.mjs';

const copy = {
  en: {
    eyebrow: 'SamChe AI Help Center', title: 'Find a verified answer.', intro: 'Navigate current product guidance, troubleshooting, and implementation boundaries grounded in the SamChe AI dashboard.', search: 'Search Help Center', placeholder: 'Search WhatsApp AI, Web Chatbot, dashboard labels, or error text…', browse: 'Browse by category', popular: 'Popular Troubleshooting', recent: 'Recently Verified', getting: 'Getting Started', noResults: 'No published guide matches this search.', support: 'Contact Support', supportText: 'If the verified steps do not resolve the issue, send your account context and visible evidence to the SamChe AI team.', askAi: 'Ask SamChe AI', askAiText: 'Describe the issue in your own words and continue with grounded guidance from these verified articles.', open: 'Read article', verified: 'Last verified', contents: 'Table of contents', prerequisites: 'Prerequisites', expected: 'Expected result', related: 'Related articles', feedback: 'Was this article helpful?', yes: 'Yes', no: 'No', thanks: 'Thanks for your feedback on this device.', back: 'Help Center', verifiedArticles: 'Published Help Articles', troubleshootingArticles: 'Troubleshooting Guides', categories: 'Categories', articles: 'articles', resultsFor: '{count} results for “{query}”', resultRange: 'Showing {start}–{end} of {total}', plan: 'Applicable plan', info: 'Information', warning: 'Important', updated: 'Verified',
  },
  tr: {
    eyebrow: 'SamChe AI Yardım Merkezi', title: 'Doğrulanmış yanıtı bulun.', intro: 'SamChe AI paneline dayanan güncel ürün rehberleri, sorun giderme adımları ve uygulama sınırları arasında gezinin.', search: 'Yardım Merkezinde ara', placeholder: 'WhatsApp AI, Web Chatbot, panel etiketi veya hata metni arayın…', browse: 'Kategorilere göre göz atın', popular: 'Popüler Sorun Giderme', recent: 'Son Doğrulananlar', getting: 'Başlangıç', noResults: 'Bu aramayla eşleşen yayınlanmış rehber yok.', support: 'Destek ekibiyle iletişime geçin', supportText: 'Doğrulanmış adımlar sorunu çözmezse hesap bağlamını ve görünen kanıtı SamChe AI ekibine gönderin.', askAi: 'SamChe AI’ye sorun', askAiText: 'Sorunu kendi kelimelerinizle açıklayın; bu doğrulanmış makalelere dayanan yönlendirmeyle devam edin.', open: 'Makaleyi aç', verified: 'Son doğrulama', contents: 'İçindekiler', prerequisites: 'Ön koşullar', expected: 'Beklenen sonuç', related: 'İlgili makaleler', feedback: 'Bu makale faydalı oldu mu?', yes: 'Evet', no: 'Hayır', thanks: 'Bu cihazdaki geri bildiriminiz için teşekkürler.', back: 'Yardım Merkezi', verifiedArticles: 'Yayınlanmış Yardım Makalesi', troubleshootingArticles: 'Sorun Giderme Rehberi', categories: 'Kategori', articles: 'makale', resultsFor: '“{query}” için {count} sonuç', resultRange: '{total} sonucun {start}–{end} arası gösteriliyor', plan: 'Geçerli paket', info: 'Bilgi', warning: 'Önemli', updated: 'Doğrulandı',
  },
  ar: {
    eyebrow: 'مركز مساعدة SamChe AI', title: 'اعثر على إجابة معتمدة.', intro: 'تصفح إرشادات المنتج الحالية وخطوات استكشاف المشكلات وحدود التنفيذ المستندة إلى لوحة SamChe AI.', search: 'البحث في مركز المساعدة', placeholder: 'ابحث عن WhatsApp AI أو Web Chatbot أو اسم في اللوحة أو نص خطأ…', browse: 'تصفح حسب الفئة', popular: 'أشهر أدلة استكشاف المشكلات', recent: 'تم التحقق منها مؤخراً', getting: 'البدء', noResults: 'لا توجد أدلة منشورة تطابق هذا البحث.', support: 'تواصل مع فريق الدعم', supportText: 'إذا لم تحل الخطوات المعتمدة المشكلة، فأرسل سياق الحساب والأدلة الظاهرة إلى فريق SamChe AI.', askAi: 'اسأل SamChe AI', askAiText: 'اشرح المشكلة بكلماتك وتابع بإرشادات تستند إلى هذه المقالات المعتمدة.', open: 'فتح المقالة', verified: 'آخر تحقق', contents: 'المحتويات', prerequisites: 'المتطلبات السابقة', expected: 'النتيجة المتوقعة', related: 'مقالات ذات صلة', feedback: 'هل كانت هذه المقالة مفيدة؟', yes: 'نعم', no: 'لا', thanks: 'شكراً لملاحظاتكم على هذا الجهاز.', back: 'مركز المساعدة', verifiedArticles: 'مقالات مساعدة منشورة', troubleshootingArticles: 'أدلة استكشاف المشكلات', categories: 'فئات', articles: 'مقالات', resultsFor: '{count} نتيجة عن «{query}»', resultRange: 'عرض {start}–{end} من {total}', plan: 'الخطة المناسبة', info: 'معلومة', warning: 'مهم', updated: 'تم التحقق',
  },
} as const;

type HelpCopy = { [key: string]: string };
type Locale = 'en' | 'tr' | 'ar';
type HelpArticleListItem = { slug: string; categoryLabel: string; articleTypeLabel: string; title: string; summary: string; verifiedOn?: string; verification?: { verifiedOn: string } };
type HelpArticleView = HelpArticleListItem & { category: string; articleType: string; navigation: string; plan: string; prerequisites: string; expected: string; related: string[]; verification: { verifiedOn: string }; sections: Array<{ heading: string; body: string; steps: string[]; note?: string; warning?: string }> };

function localizedArticleUrl(slug: string, locale: Locale) { return `/help/article/${slug}${locale === 'en' ? '' : `?locale=${locale}`}`; }
function formatCopy(template: string, values: Record<string, string | number>) { return Object.entries(values).reduce((value, [key, replacement]) => value.replace(`{${key}}`, String(replacement)), template); }

function SearchForm({ initial = '' }: { initial?: string }) {
  const { locale } = useSiteLocale();
  const text = copy[locale] as HelpCopy;
  const [query, setQuery] = useState(() => initial || (typeof window !== 'undefined' ? new URLSearchParams(window.location.search).get('q') || '' : ''));
  const [submitted, setSubmitted] = useState(() => initial || (typeof window !== 'undefined' ? new URLSearchParams(window.location.search).get('q') || '' : ''));
  const results = useMemo(() => searchHelpArticleResults(submitted, locale, { limit: 20 }), [submitted, locale]);
  const suggestions = useMemo(() => searchHelpArticles(query, locale, { limit: 5 }), [query, locale]);
  function submit(event: FormEvent) { event.preventDefault(); const value = query.trim(); setSubmitted(value); if (typeof window !== 'undefined') window.history.pushState({}, '', value ? `/help?locale=${locale}&q=${encodeURIComponent(value)}` : `/help?locale=${locale}`); }
  return <section className="help-search" aria-labelledby="help-search-title">
    <h2 id="help-search-title" className="sr-only">{text.search}</h2>
    <form onSubmit={submit} role="search" className="help-search-form"><label htmlFor="help-search-input" className="sr-only">{text.search}</label><input id="help-search-input" type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder={text.placeholder} aria-controls="help-search-suggestions" aria-autocomplete="list" /><button className="button button-primary button-small" type="submit">{text.search}</button></form>
    {query.trim() && <div id="help-search-suggestions" className="help-search-suggestions" role="listbox" aria-label={text.search}>{suggestions.length ? suggestions.map((result) => <Link role="option" aria-selected="false" key={result.slug} className="help-search-suggestion" href={result.url}><span className="help-row-meta"><span>{result.categoryLabel}</span><span>{result.articleTypeLabel}</span></span><strong>{result.title}</strong><small>{result.excerpt}</small></Link>) : <p className="help-empty">{text.noResults}</p>}</div>}
    {submitted && <div className="help-search-results" aria-live="polite"><div className="help-search-summary"><strong>{formatCopy(text.resultsFor, { count: results.total, query: results.query })}</strong>{results.total > 0 && <span>{formatCopy(text.resultRange, { start: results.start, end: results.end, total: results.total })}</span>}</div>{results.items.length ? <div className="help-article-list">{results.items.map((result) => <ArticleRow key={result.slug} article={result} href={result.url} text={text} />)}</div> : <p className="help-empty">{text.noResults}</p>}</div>}
  </section>;
}

function ArticleRow({ article, href, text }: { article: HelpArticleListItem; href: string; text: HelpCopy }) {
  const verifiedOn = article.verification?.verifiedOn || article.verifiedOn;
  return <Link className="help-article-row" href={href}><span className="help-row-content"><span className="help-row-meta"><span>{article.categoryLabel}</span><span>{article.articleTypeLabel}</span>{verifiedOn && <span>{text.updated} {verifiedOn}</span>}</span><strong>{article.title}</strong><small>{article.summary}</small></span><span className="help-row-arrow" aria-hidden="true">→</span></Link>;
}

function PortalArticleSection({ id, title, articles, locale, text }: { id: string; title: string; articles: HelpArticleView[]; locale: Locale; text: HelpCopy }) {
  return <section className="help-section" aria-labelledby={id}><div className="help-section-heading"><h2 id={id}>{title}</h2><span>{articles.length}</span></div><div className="help-article-list">{articles.map((article) => <ArticleRow key={article.slug} article={article} href={localizedArticleUrl(article.slug, locale)} text={text} />)}</div></section>;
}

function HelpActions({ text }: { text: HelpCopy }) { return <div className="help-actions"><section className="help-ask-ai"><div><h2>{text.askAi}</h2><p>{text.askAiText}</p></div><button className="button button-primary" type="button" onClick={() => window.dispatchEvent(new Event('samche:open-chat'))}>{text.askAi} <span aria-hidden="true">↗</span></button></section><HelpContact text={text} /></div>; }
function HelpContact({ text }: { text: HelpCopy }) { return <section className="help-contact"><div><h2>{text.support}</h2><p>{text.supportText}</p></div><Link className="button button-outline" href="/support#submit-ticket">{text.support} <span aria-hidden="true">↗</span></Link></section>; }

export function HelpCenterHome({ initialQuery = '' }: { initialQuery?: string }) {
  const { locale } = useSiteLocale(); const text = copy[locale] as HelpCopy; const categories = getPublishedCategories(locale); const articles = getPublishedArticles(locale) as HelpArticleView[]; const statistics = getHelpCenterStats(locale);
  const popular = ['whatsapp-ai-not-replying', 'web-chatbot-not-appearing', 'knowledge-pdf-old-price', 'ai-visual-no-output', 'lead-not-visible'].map((slug) => articles.find((article) => article.slug === slug)).filter(Boolean) as HelpArticleView[];
  const recent = [...articles].sort((a, b) => b.verification.verifiedOn.localeCompare(a.verification.verifiedOn) || a.title.localeCompare(b.title)).slice(0, 5); const gettingStarted = articles.filter((article) => article.category === 'getting-started').slice(0, 5);
  return <div className="help-center" dir={locale === 'ar' ? 'rtl' : 'ltr'}><main id="main-content" className="help-home page-width"><section className="help-hero"><p className="eyebrow"><span aria-hidden="true" />{text.eyebrow}</p><h1>{text.title}</h1><p>{text.intro}</p><SearchForm initial={initialQuery} /></section><section className="help-metric-grid" aria-label={`${statistics.totalPublished} ${text.verifiedArticles}`}><div><strong>{statistics.totalPublished}</strong><span>{text.verifiedArticles}</span></div><div><strong>{statistics.totalTroubleshooting}</strong><span>{text.troubleshootingArticles}</span></div><div><strong>{statistics.totalCategories}</strong><span>{text.categories}</span></div></section><section className="help-section" aria-labelledby="help-categories"><div className="help-section-heading"><div><p className="eyebrow"><span aria-hidden="true" />{text.categories}</p><h2 id="help-categories">{text.browse}</h2></div><span>{statistics.totalCategories}</span></div><div className="help-category-grid">{categories.map((category) => <Link key={category.slug} href={`/help/category/${category.slug}${locale === 'en' ? '' : `?locale=${locale}`}`} className="help-category-card"><span className="help-category-icon" aria-hidden="true">{category.label.slice(0, 1)}</span><span className="help-category-copy"><strong>{category.label}</strong><span>{category.description}</span><small>{category.articleCount} {text.articles}</small></span><span className="help-row-arrow" aria-hidden="true">→</span></Link>)}</div></section><PortalArticleSection id="help-popular" title={text.popular} articles={popular} locale={locale} text={text} /><PortalArticleSection id="help-recent" title={text.recent} articles={recent} locale={locale} text={text} /><PortalArticleSection id="help-getting-started" title={text.getting} articles={gettingStarted} locale={locale} text={text} /><HelpActions text={text} /></main></div>;
}

export function HelpCategoryClient({ categorySlug }: { categorySlug: string }) {
  const { locale } = useSiteLocale(); const text = copy[locale] as HelpCopy; const category = getCategoryBySlug(categorySlug, locale); const groups = getCategoryArticleGroups(categorySlug, locale) as Array<{ key: string; label: string; articles: HelpArticleView[] }>;
  if (!category) return <main className="help-home page-width"><HelpContact text={text} /></main>;
  return <div className="help-center" dir={locale === 'ar' ? 'rtl' : 'ltr'}><main id="main-content" className="help-home page-width"><div className="help-breadcrumbs"><Link href={`/help${locale === 'en' ? '' : `?locale=${locale}`}`}>{text.back}</Link><span aria-hidden="true">/</span><span>{category.label}</span></div><section className="help-hero help-hero-compact"><p className="eyebrow"><span aria-hidden="true" />{text.browse}</p><h1>{category.label}</h1><p>{category.description}</p><p className="help-category-count"><strong>{category.articles.length}</strong> {text.articles}</p><SearchForm /></section>{groups.map((group) => <section className="help-section help-category-group" key={group.key}><div className="help-section-heading"><h2>{group.label}</h2><span>{group.articles.length}</span></div><div className="help-article-list">{group.articles.map((article) => <ArticleRow key={article.slug} article={article} href={localizedArticleUrl(article.slug, locale)} text={text} />)}</div></section>)}<HelpActions text={text} /></main></div>;
}

export function HelpArticleClient({ slug }: { slug: string }) {
  const { locale } = useSiteLocale(); const text = copy[locale] as HelpCopy; const articleRecord = getArticleBySlug(slug, locale); if (!articleRecord) return <main className="help-home page-width"><HelpContact text={text} /></main>; const article = articleRecord as HelpArticleView; const related = [...new Set(article.related)].map((relatedSlug) => getArticleBySlug(relatedSlug, locale) as HelpArticleView | null).filter(Boolean) as HelpArticleView[];
  return <div className="help-center" dir={locale === 'ar' ? 'rtl' : 'ltr'}><main id="main-content" className="help-home page-width"><div className="help-breadcrumbs"><Link href={`/help${locale === 'en' ? '' : `?locale=${locale}`}`}>{text.back}</Link><span aria-hidden="true">/</span><Link href={`/help/category/${article.category}${locale === 'en' ? '' : `?locale=${locale}`}`}>{article.categoryLabel}</Link><span aria-hidden="true">/</span><span>{article.title}</span></div><div className="help-article-layout"><aside className="help-article-sidebar"><strong>{text.contents}</strong><nav aria-label={text.contents}><ol>{article.sections.map((section, sectionIndex) => <li key={`${section.heading}-${sectionIndex}`}><a href={`#section-${sectionIndex}`}>{section.heading}</a></li>)}</ol></nav></aside><article className="help-article"><p className="eyebrow"><span aria-hidden="true" />{article.categoryLabel} · {article.articleTypeLabel}</p><h1>{article.title}</h1><p className="help-article-summary">{article.summary}</p><div className="help-article-meta"><span><strong>{text.plan}:</strong> {article.plan}</span><span><strong>{text.verified}:</strong> {article.verification.verifiedOn}</span></div><div className="help-fact-grid"><div><strong>{text.prerequisites}</strong><p>{article.prerequisites}</p></div><div><strong>{text.expected}</strong><p>{article.expected}</p></div></div>{article.sections.map((section, sectionIndex) => <section className="help-article-section" id={`section-${sectionIndex}`} key={`${section.heading}-${sectionIndex}`}><h2>{section.heading}</h2><p>{section.body}</p>{section.steps.length > 0 && <ol>{section.steps.map((step, stepIndex) => <li key={`${step}-${stepIndex}`}>{step}</li>)}</ol>}{section.note && <aside className="help-notice help-notice-info"><strong>{text.info}</strong><p>{section.note}</p></aside>}{section.warning && <aside className="help-notice help-notice-warning"><strong>{text.warning}</strong><p>{section.warning}</p></aside>}</section>)}<section className="help-feedback" aria-label={text.feedback}><p>{text.feedback}</p><button type="button" onClick={(event) => { event.currentTarget.parentElement?.setAttribute('data-feedback', 'yes'); }}>{text.yes}</button><button type="button" onClick={(event) => { event.currentTarget.parentElement?.setAttribute('data-feedback', 'no'); }}>{text.no}</button><small>{text.thanks}</small></section>{related.length > 0 && <section className="help-related"><div className="help-section-heading"><h2>{text.related}</h2><span>{related.length}</span></div><div className="help-article-list">{related.map((relatedArticle) => <ArticleRow key={relatedArticle.slug} article={relatedArticle} href={localizedArticleUrl(relatedArticle.slug, locale)} text={text} />)}</div></section>}<HelpActions text={text} /></article></div></main></div>;
}
