import type { Metadata } from 'next';
import Link from './components/internal-link';
import { addons, demoLinks, plans } from '../lib/site-data.mjs';
import { PricingTable } from './components/pricing-table';
import { ProductScreenshot } from './components/product-screenshot';
import { ProductCTA, SectionEyebrow, SiteShell } from './components/site-shell';

export const metadata: Metadata = {
  title: 'SamChe AI Platform | One AI Platform. Every Customer Conversation.',
  description: 'SamChe AI is a multi-tenant subscription SaaS platform for AI Assistants, Knowledge Intelligence, customer conversations, CRM and AI Guide experiences.',
  alternates: { canonical: 'https://samche.ai/' },
  openGraph: { title: 'SamChe AI Platform', description: 'AI customer operations in one multi-tenant SaaS workspace.', url: 'https://samche.ai/', siteName: 'SamChe AI', type: 'website' },
};

const capabilities = [
  ['01', 'AI Assistants', 'Configure business-specific assistants and manage their behavior from the tenant workspace.'],
  ['02', 'Knowledge Intelligence', 'Manage knowledge sources, processing states and grounded retrieval previews.'],
  ['03', 'Live Inbox', 'Review conversations, reply as a team, and manage AI or human handling where supported.'],
  ['04', 'CRM & Pipeline', 'Work with leads and pipeline records inside the workspace.'],
  ['05', 'AI Guide', 'Configure customer-facing, guided AI experiences beyond a simple Q&A exchange.'],
  ['06', 'Tenant Analytics', 'See workspace KPIs and date-filtered analytics in the dashboard.'],
  ['07', 'Multi-channel AI', 'Bring Web Chatbot, WhatsApp AI and AI Guide into connected customer operations.'],
  ['08', 'Tenant workspaces', 'Keep product areas organized around a customer workspace and its configuration.'],
];

const workflow = ['Connect business knowledge', 'Configure an AI assistant', 'Deploy a customer channel', 'Handle conversations', 'Review leads and follow-up', 'Manage from the workspace'];

function LiveProductVisual({ crop, alt, capturedAsset }: { crop: 'web' | 'guide' | 'whatsapp'; alt: string; capturedAsset: string }) {
  return <div className={`live-product-visual live-product-visual-${crop}`} role="img" aria-label={alt} data-captured-asset={capturedAsset} />;
}

export default function HomePage() {
  return <SiteShell><main id="main-content">
    <section className="new-hero page-width">
      <div className="new-hero-copy"><SectionEyebrow>SamChe AI Platform · Multi-tenant SaaS</SectionEyebrow>
        <h1>ONE AI PLATFORM.<br /><em>AUTOMATE CUSTOMER COMMUNICATION,</em><br />WORKFLOWS AND OPERATIONS.</h1>
        <p>SamChe AI brings AI assistants, customer conversations, business knowledge, CRM and customer operations together in one multi-tenant SaaS workspace. It supports today’s customer-facing AI experiences while clearly separating roadmap capabilities, including agentic workflows, Skills, Actions and the Workflow Engine.</p>
        <div className="hero-actions"><ProductCTA href="/platform">Explore the Platform</ProductCTA><a className="button button-outline" href="#live-products">Try Live Demos <span aria-hidden="true">↓</span></a><ProductCTA href="/pricing" secondary>See Pricing</ProductCTA></div>
        <div className="hero-facts"><span>SUBSCRIPTION SOFTWARE</span><span>MULTI-TENANT WORKSPACES</span><span>CONNECTED AI PRODUCTS</span></div>
      </div>
      <div className="new-hero-evidence"><ProductScreenshot className="hero-product-shot" alt="Verified SamChe AI Knowledge Intelligence screen with sample workspace details redacted" caption="Real SamChe AI product screen · Knowledge Intelligence" /><div className="evidence-tag"><span className="signal-dot" /> REAL PRODUCT EVIDENCE <span>·</span> TENANT DASHBOARD</div></div>
    </section>

    <section className="platform-capability-rail page-width" aria-labelledby="core-capabilities-heading">
      <div className="platform-capability-intro"><SectionEyebrow>CORE PLATFORM CAPABILITIES · AI ASSISTANTS · KNOWLEDGE INTELLIGENCE · LIVE INBOX · CRM &amp; PIPELINE · AI GUIDE</SectionEyebrow><h2 id="core-capabilities-heading">AI assistants, conversations, knowledge and leads in one system.</h2><p>SamChe AI connects customer-facing AI, approved business knowledge, centralized inbox operations and lead workflows inside one subscription platform.</p></div>
      <div className="platform-capability-grid">{capabilities.slice(0, 5).map(([number, title, description]) => <article key={title}><span>{number}</span><h3>{title.toUpperCase()}</h3><p>{description}</p><b aria-hidden="true">↗</b></article>)}</div>
    </section>

    <section className="section page-width" id="live-products"><div className="section-heading"><div><SectionEyebrow>01 · LIVE PRODUCTS · CURRENT COMMERCIAL</SectionEyebrow><h2>Live AI experiences.<br /><em>One operating platform.</em></h2></div><p>Explore the customer-facing products connected to SamChe AI. Each experience serves a distinct purpose and sits within a broader platform for assistants, conversations, knowledge and leads.</p></div>
      <div className="live-products-grid">
        <article className="live-product product-chatbot" id="web-chatbot-demo"><div className="product-card-top"><span>01 / WEBSITE</span><span className="live-badge"><i /> VERIFIED LIVE DEMO</span></div><LiveProductVisual crop="web" capturedAsset="/assets/product/web-chatbot-real.png" alt="Real Web Chatbot UI screenshot from the approved SamChe public demo" /><div className="product-glyph">↗</div><h3>Web Chatbot</h3><p>AI-powered website conversations for product discovery, business information, lead capture and customer assistance.</p><ul><li>Real-time website conversations</li><li>Business-aware answers from approved knowledge</li><li>Lead capture and human handover where configured</li></ul><a className="product-link" href={demoLinks.webChatbot} target="_blank" rel="noreferrer">TRY WEB CHATBOT <span>↗</span></a></article>
        <article className="live-product product-guide"><div className="product-card-top"><span>02 / GUIDED EXPERIENCE</span><span className="live-badge verified"><i /> VERIFIED PUBLIC GUIDE</span></div><LiveProductVisual crop="guide" capturedAsset="/assets/product/ai-guide-real.png" alt="Real AI Guide UI screenshot from the approved Blue Dune public guide" /><div className="product-glyph">◎</div><h3>AI Guide</h3><p>A guided AI experience for structured journeys, recommendations, contextual planning and branded customer assistance.</p><ul><li>Guided journeys and recommendation flows</li><li>Structured assistance and contextual planning</li><li>Existing public AI Guide experience</li></ul><a className="product-link" href={demoLinks.aiGuide} target="_blank" rel="noreferrer">TRY AI GUIDE <span>↗</span></a></article>
        <article className="live-product product-whatsapp"><div className="product-card-top"><span>03 / MESSAGING</span><span className="live-badge verified"><i /> VERIFIED DEMO CHANNEL</span></div><LiveProductVisual crop="whatsapp" capturedAsset="/assets/product/product-cards-reference.png" alt="Real WhatsApp AI product conversation visual from the approved SamChe product reference" /><div className="product-glyph">◌</div><h3>WhatsApp AI</h3><p>Business-aware messaging connected to shared platform knowledge and centralized conversation operations.</p><ul><li>Automated WhatsApp conversations</li><li>Shared AI and team workflow</li><li>Centralized handling of customer enquiries</li></ul><a className="product-link" href={demoLinks.whatsapp} target="_blank" rel="noreferrer">TRY WHATSAPP AI <span>↗</span></a></article>
      </div>
    </section>

    <section className="dashboard-feature-section"><div className="page-width dashboard-feature-inner"><div className="section-heading"><div><SectionEyebrow>02 · Multi-tenant control plane</SectionEyebrow><h2>ONE DASHBOARD.<br /><em>ALL AI OPERATIONS.</em></h2></div><p>Manage assistants, knowledge, channels, conversations, leads, pipeline, analytics and workspace configuration from a central tenant workspace.</p></div><ProductScreenshot className="dashboard-large-shot" alt="Actual SamChe AI Knowledge Intelligence screen, shown as product evidence with private sample data obscured" caption="Actual SamChe AI Platform screen · Knowledge Intelligence · workspace details obscured for privacy" /><div className="dashboard-capability-grid">{['AI Assistants', 'Web Chatbot', 'WhatsApp AI', 'AI Guide', 'Knowledge Intelligence', 'Live Inbox', 'Leads & Pipeline', 'Tenant analytics', 'Team / workspace settings'].map((item) => <span key={item}><i>↗</i>{item}</span>)}</div><Link className="text-link" href="/platform">EXPLORE PLATFORM ARCHITECTURE <span>↗</span></Link></div></section>

    <section className="section page-width" id="platform-capabilities"><div className="section-heading"><div><SectionEyebrow>03 · Platform capabilities</SectionEyebrow><h2>Connected modules.<br /><em>One product system.</em></h2></div><p>Product areas share a tenant context. The current dashboard implementation includes the modules below; Automation / Agentic AI remains on the roadmap.</p></div><div className="capability-grid">{capabilities.map(([n, title, desc]) => <article className="capability-card" key={title}><span>{n}</span><h3>{title}</h3><p>{desc}</p><b aria-hidden="true">↗</b></article>)}</div></section>

    <section className="workflow-section"><div className="page-width"><div className="section-heading"><div><SectionEyebrow>04 · How SamChe AI works</SectionEyebrow><h2>From business knowledge<br /><em>to customer operations.</em></h2></div><p>Configure the available product modules around your customer journey, then manage conversations and leads within the workspace.</p></div><ol className="workflow-list">{workflow.map((step, i) => <li key={step}><span>0{i + 1}</span><strong>{step}</strong><i aria-hidden="true">↗</i></li>)}</ol></div></section>

    <section className="section page-width evidence-gallery"><div className="section-heading"><div><SectionEyebrow>05 · REAL PRODUCT SCREENSHOTS</SectionEyebrow><h2>Product evidence,<br /><em>not concept screens.</em></h2></div><p>The currently verified public asset is from the Knowledge Intelligence module. We found no publishable dashboard, Inbox, assistant, Guide or CRM screenshot in the searched product repositories, so those screens are not fabricated.</p></div><ProductScreenshot className="gallery-feature-shot" alt="Verified SamChe AI Knowledge Intelligence screenshot, with tenant and source details obscured" caption="Verified existing SamChe AI product-marketing asset · Knowledge Intelligence" /><div className="evidence-caption-row"><span>VERIFIED EXISTING ASSET</span><span>PRIVATE SAMPLE DETAILS OBSCURED</span><Link href="/contact">Request a guided product demo ↗</Link></div></section>

    <section className="feature-story page-width"><div className="feature-story-copy"><SectionEyebrow>06 · Web Chatbot</SectionEyebrow><h2>Answer the question.<br /><em>Keep the conversation moving.</em></h2><p>SamChe Web Chatbot is designed for website Q&amp;A, support and lead capture, with business knowledge connected to the assistant. Page-aware context and human handover are available where supported by the selected setup.</p><div className="story-points"><span>01 <b>Website customer assistance</b></span><span>02 <b>Business knowledge context</b></span><span>03 <b>Lead capture and handover</b></span></div><a className="button button-primary" href={demoLinks.webChatbot} target="_blank" rel="noreferrer">Try Web Chatbot <span>↗</span></a></div><div className="story-visual story-web"><span>WEB CHATBOT</span><strong>Business-aware<br />website assistance</strong><small>Managed through SamChe AI Platform</small><div className="story-orbit orbit-one"/><div className="story-orbit orbit-two"/></div></section>

    <section className="feature-story feature-story-guide page-width"><div className="story-visual story-guide"><span>AI GUIDE</span><strong>Guided journeys<br />for richer decisions</strong><small>Real public Guide experience</small><div className="guide-modes"><span>ROADMAP</span><span>PLANNING</span><span>ASSISTANT</span><span>ANALYZE</span></div></div><div className="feature-story-copy"><SectionEyebrow>07 · AI Guide</SectionEyebrow><h2>More than a chatbot.<br /><em>A guided AI experience.</em></h2><p>The existing public AI Guide demonstrates structured planning, business-specific guidance, contextual assistance and interactive customer journeys with its own customer-facing branding.</p><div className="story-points"><span>01 <b>Structured customer journeys</b></span><span>02 <b>Interactive recommendations</b></span><span>03 <b>Branded customer experience</b></span></div><a className="button button-primary" href={demoLinks.aiGuide} target="_blank" rel="noreferrer">Try AI Guide <span>↗</span></a></div></section>

    <section className="section page-width comparison-products"><div className="section-heading"><div><SectionEyebrow>WEB CHATBOT VS AI GUIDE</SectionEyebrow><h2>Two products.<br /><em>Different customer needs.</em></h2></div><p>Choose a quick response path for common website questions, or a guided experience for decisions that benefit from structured customer journeys.</p></div><div className="experience-compare"><article><span>WEB CHATBOT</span><h3>Fast answers on your website.</h3><p>Best for support, product and service questions, business information and lead capture.</p><ul><li>Website Q&amp;A</li><li>Service and product questions</li><li>Page-aware assistance where supported</li></ul></article><div className="compare-mark">OR</div><article><span>AI GUIDE</span><h3>Guided help for complex choices.</h3><p>Best for planning, interactive recommendations, project or service selection and richer branded journeys.</p><ul><li>Structured customer journeys</li><li>Contextual recommendations</li><li>Interactive planning modes</li></ul></article></div></section>

    <section className="section page-width knowledge-section"><div className="section-heading"><div><SectionEyebrow>08 · Knowledge Intelligence</SectionEyebrow><h2>Business knowledge,<br /><em>available to AI.</em></h2></div><p>Manage knowledge sources, inspect processing/indexing states and use retrieval previews in the existing product workflow. Supported formats and results depend on workspace configuration.</p></div><div className="knowledge-proof"><ProductScreenshot className="knowledge-shot" alt="Real Knowledge Intelligence product interface with private example source details obscured" caption="Real Knowledge Intelligence product screen" /><div className="knowledge-points"><div><span>01</span><h3>Manage sources</h3><p>Review the knowledge sources available in a tenant workspace.</p></div><div><span>02</span><h3>Follow processing</h3><p>See source processing and indexing states in the product.</p></div><div><span>03</span><h3>Preview retrieval</h3><p>Test the supported retrieval preview workflow for grounded answers.</p></div><Link className="text-link" href="/platform">SEE PLATFORM DETAILS ↗</Link></div></div></section>

    <section className="inbox-section"><div className="page-width"><div className="section-heading"><div><SectionEyebrow>09 · LIVE INBOX + CRM</SectionEyebrow><h2>Turn conversations into<br /><em>team follow-through.</em></h2></div><p>Review conversations and team replies in Live Inbox, then work with leads and pipeline records within the same tenant context.</p></div><div className="inbox-flow"><article><span>01 / CONVERSATION</span><h3>Live Inbox</h3><p>Review channel conversations and take over handling where supported.</p></article><i>→</i><article><span>02 / CUSTOMER SIGNAL</span><h3>Leads</h3><p>Manage leads in a workspace-scoped view.</p></article><i>→</i><article><span>03 / FOLLOW-UP</span><h3>Pipeline</h3><p>Track pipeline records through product workflows.</p></article></div><Link className="text-link" href="/platform">EXPLORE LIVE INBOX &amp; CRM ↗</Link></div></section>

    <section className="section page-width verticals-section"><div className="section-heading"><div><SectionEyebrow>10 · Built for customer-facing teams</SectionEyebrow><h2>AI operations for<br /><em>many business models.</em></h2></div><p>Standardized product tiers support businesses that handle customer questions, guidance, lead capture and follow-up.</p></div><div className="vertical-list">{['Real Estate', 'Hospitality', 'Professional Services', 'Automotive', 'Healthcare', 'E-commerce', 'Startups & SMEs'].map((item, i) => <span key={item}><small>0{i + 1}</small>{item}<b>↗</b></span>)}</div><p className="vertical-note">Product suitability depends on configuration and the customer’s own operating requirements. No sector-specific compliance certification is implied.</p></section>

    <section className="home-pricing-section" id="pricing"><div className="page-width"><div className="section-heading"><div><SectionEyebrow>11 · Subscription pricing</SectionEyebrow><h2>Clear plans.<br /><em>Room to scale.</em></h2></div><p>Choose the approved monthly or yearly subscription. Implementation &amp; onboarding is shown separately as a one-time charge. Every interaction allowance remains monthly.</p></div><PricingTable /><div className="which-plan"><div><SectionEyebrow>12 · Choose your starting point</SectionEyebrow><h2>Which plan is right for you?</h2></div><div className="which-plan-grid">{plans.map((plan) => <Link className={`which-plan-item plan-${plan.slug}`} href={`/contact?plan=${plan.slug}`} key={plan.slug}><b>{plan.name}</b><span>{plan.description}</span><i>Explore plan ↗</i></Link>)}</div></div></div></section>

    <section className="section page-width addon-callout"><div className="section-heading"><div><SectionEyebrow>13 · Optional platform add-ons</SectionEyebrow><h2>Extend the platform<br /><em>where you need it.</em></h2></div><Link className="text-link" href="/pricing">SEE ADD-ON DETAILS ↗</Link></div><div className="addon-preview-grid">{addons.map((addon) => <article key={addon.name}><span>ADD-ON</span><h3>{addon.name}</h3><strong>{addon.price}</strong><p>{addon.description}</p></article>)}</div><p className="addon-footnote">Outbound AI Calling from AED 3.49/min. Telecom setup conditions, third-party messaging fees, and setup costs vary by scope. <Link href="/pricing">Full pricing notes ↗</Link></p></section>

    <section className="roadmap-section"><div className="page-width roadmap-inner"><div><SectionEyebrow>14 · Product roadmap</SectionEyebrow><h2>What’s next.<br /><em>Clearly labeled.</em></h2><p>Custom Workflows are available today for configured automations and integrations. Agentic AI, Skills, Actions and the broader Workflow Engine remain roadmap capabilities.</p></div><div className="roadmap-status"><span>ROADMAP / UPCOMING</span><h3>Agentic AI · Skills · Actions · Workflow Engine</h3><p>Separately scoped development or integration work does not include the future roadmap product entitlement.</p></div></div></section>

    <section className="security-brief page-width"><div><SectionEyebrow>15 · Security &amp; privacy</SectionEyebrow><h2>A clear tenant model.<br /><em>A factual security posture.</em></h2><p>SamChe AI is a multi-tenant platform with tenant-scoped product workflows. Public materials avoid unverified certification, encryption, residency or retention guarantees.</p></div><div className="security-links"><Link href="/security">Explore Security &amp; Privacy <span>↗</span></Link><Link href="/privacy">Read the Privacy Policy <span>↗</span></Link><a href="mailto:support@samchecompany.com">Email support@samchecompany.com <span>↗</span></a></div></section>

    <section className="final-cta"><div className="page-width final-cta-inner"><SectionEyebrow>16 · Put SamChe AI to work</SectionEyebrow><h2>Bring AI into<br /><em>customer operations.</em></h2><p>Explore the platform, try the verified customer-facing experiences, or speak with the product team about plans.</p><div className="hero-actions"><ProductCTA href="/contact">Request Demo</ProductCTA><a className="button button-outline" href="mailto:sales@samche.ai">sales@samche.ai <span>↗</span></a></div><small>Demo and plan enquiries do not purchase or activate a subscription.</small></div></section>
    <div className="support-strip page-width"><span>PRODUCT DEMOS &amp; PLANS</span><a href="mailto:sales@samche.ai">sales@samche.ai</a><span>PRODUCT SUPPORT</span><a href="mailto:support@samchecompany.com">support@samchecompany.com</a></div>
  </main></SiteShell>;
}
