export type Plan = {
  slug: string;
  name: string;
  description: string;
  monthly: number;
  setup: number;
  interactions: string;
  yearly: number;
  cta: string;
  badge?: string;
  from?: boolean;
  setupNote?: string;
  supportLevel: string;
  implementationLabel: string;
  implementationNote: string;
  supportEntitlements: string[];
  features: string[];
};
export const plans: Plan[];
export const addons: { name: string; price: string; setup?: string; description: string }[];
export const addonNotes: string[];
export const productModules: { name: string; status: string; description: string }[];
export const planInheritanceNotes: string[];
export const comparisonStateLegend: { state: string; description: string }[];
export const agenticExpansionNote: string;
export const platformFeatureGroups: { label: string; rows: { label: string; values: string[] }[] }[];
export const planComparisonRows: { label: string; values: string[] }[];
export const comparisonUsageNotes: string[];
export const interactionAllowanceCards: { title: string; body: string }[];
export const demoLinks: { webChatbot: string; whatsapp: string; aiGuide: string };
export const productScreenshots: { knowledgeIntelligence: string };
export function planFromSearch(search: string): string;
export function yearlyPrice(plan: Plan): string;
export function monthlyPrice(plan: Plan): string;
export function setupPrice(plan: Plan): string;
